"""empty message

Revision ID: 12ce0b58ec95
Revises: c91a856a4bd6
Create Date: 2019-06-30 17:05:37.194233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ce0b58ec95'
down_revision = 'c91a856a4bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'products', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'slug')
    # ### end Alembic commands ###
