"""add img

Revision ID: 695febf3ca1c
Revises: b051d552330e
Create Date: 2019-06-17 00:12:12.027620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695febf3ca1c'
down_revision = 'b051d552330e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_picture',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['img_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'img_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_picture')
    # ### end Alembic commands ###
